config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :about, only: %i(index)
  resources :charts, only: %i(new create show)
  resources :feedbacks, only: %i(create)
end

app/models/chart.rb
class Chart
  include CacheStorage

  attr_accessor :title, :subtitle, :point_start, :series, :type, :y_axis, :added_at

  alias :id :cache_key
  alias :id= :cache_key=

  DEFAULT_TYPE     = 'spline'
  DEFAULT_SUBTITLE = 'Spline Chart'
  DEFAULT_Y_AXIS   = 'Values'

  DEFAULT_SERIES_NUMBER = 10

  # params{ title:, subtitle:, point_start:, series:, type:, ... }
  def initialize(params)
    @title       = params[:title]
    @subtitle    = params[:subtitle].presence || DEFAULT_SUBTITLE
    @point_start = params[:point_start]
    @series      = params[:series]
    @type        = params[:type].presence     || DEFAULT_TYPE
    @y_axis      = params[:y_axis].presence   || DEFAULT_Y_AXIS
    @cache_key   = generate_cache_key
    @added_at    = params[:added_at].presence || Time.now
  end

  def expires_at
    Time.at(added_at.to_time.to_i + CHART_EXPIRATION)
  end

  def split
    @series.in_groups_of(DEFAULT_SERIES_NUMBER, false).map do |series_group|
      self.class.new({
        title:       @title,
        subtitle:    @subtitle,
        point_start: @point_start,
        series:      series_group,
        type:        @type,
        y_axis:      @y_axis,
        added_at:    self.added_at
      })
    end
  end

  def splittable?
    @series.size > DEFAULT_SERIES_NUMBER
  end

  def to_json
    {
      title:       title,
      subtitle:    subtitle,
      point_start: point_start,
      series:      series,
      type:        type,
      y_axis:      y_axis,
      added_at:    added_at
    }.to_json
  end

  def self.initialize_with_id(id)
    data = JSON.parse(self.fetch_from_cache(id)) rescue {}
    return if data.blank?
    self.new(data.deep_symbolize_keys)
  end

  # params{ title: '', subtitle: '', type: '', file:, ... }
  def self.initialize_from_params(params)
    data = RawDataProcessor.new(params['file']).process
    self.new({
      title:       params['title'],
      subtitle:    params['subtitle'],
      point_start: self.get_point_start(data),
      series:      self.convert_to_series(data),
      type:        params['type'],
      y_axis:      params['y_axis']
    })
  end

  private

    def self.convert_to_series(data)
      data.map{ |name, _data| { name: name, data: _data.values.map(&:to_f) } }
    end

    def self.get_point_start(data)
      data.first[1].keys.first
    end

end

app/models/concerns/cache_storage.rb
module CacheStorage
  extend ActiveSupport::Concern

  included do
    CHART_EXPIRATION = 1.hour
    attr_accessor :cache_key
  end

  def store
    @cache_key = generate_cache_key
    return true if Rails.cache.exist?(@cache_key)
    Rails.cache.write(@cache_key, self.to_json, expires_in: CHART_EXPIRATION)
  end

  module ClassMethods
    def fetch_from_cache(cache_key)
      Rails.cache.read(cache_key)
    end
  end

  private
    def generate_cache_key
      Digest::SHA1.hexdigest self.to_json
    end
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  validates :user_name, presence: true
  validates :user_email, presence: true, format: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :body, presence: true

  def send_to_author!
    ColleaguesMailer.feedback(self).deliver!
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def new
  end

  def create
    chart = Chart.initialize_from_params(chart_params)
    chart.store
    redirect_to chart_path(chart.id)
  rescue StandardError => error
    Rails.logger.debug error.message
    Rails.logger.debug error.backtrace[0..3].join("\n\t\t\t")
    flash[:danger] = "Коллега, что-то пошло не так. Попробуйте еще раз"
    redirect_to new_chart_path
  end

  def show
    chart = Chart.initialize_with_id(params[:id])
    if chart.blank?
      flash[:warning] = "Коллега, либо данных нет, либо срок их хранения закончился. Попробуйте снова!"
      redirect_to(new_chart_path) and return
    end
    @charts = chart.splittable? ? chart.split : [chart]
  end

  private
    def chart_params
      params[:chart][:file] = params[:chart][:file].tempfile
      params.require(:chart).permit!
    end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  def create
    Feedback.create(feedback_params).send_to_author!
    head :ok
  rescue => e
    render json: { message: e.message }, status: :bad_request
  end

  private

    def feedback_params
      params.require(:feedback).permit(:user_name, :user_email, :body)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.haml
.container
  .page-header
    %h2 About Project

  .row
    .col-xs-12
      %h4.about-description
        Сервис, который поможет коллегам запилить график.
        .clearfix
        - url = ZapiliCollegeGraphik.colleague_profile_endpoint
        Идея сервиса появилась после того, как уважаемый коллега (#{ link_to 'Дмитрий Белоус', url }) нуждался в графиках и даже всемогущие
        %i
          Microsoft Excel 2013
        - url = ZapiliCollegeGraphik.opu_endpoint
        и диплом #{ link_to 'Политеха', url } не смогли быстро помочь в этом деле.
      .clearfix

      .page-header
        %h4 Есть идеи, как сделать сервис лучше?

      .row
        .col-md-6.col-xs-12
          .panel.panel-default
            .panel-heading
              %h4
                Запили коллеге
                = link_to ZapiliCollegeGraphik.new_issue_endpoint do
                  Issue
                  %span.fa.fa-bitbucket
            %ul.list-group
              %li.list-group-item 1. Запили краткий и понятный заголовок
              %li.list-group-item 2. Запили полное описание
              %li.list-group-item 3. Выбери тип proposal (предложение)
              %li.list-group-item 4. Считаешь, что скриншотик будет полезным? You're welcome!
              %li.list-group-item 5. Жми "Создать"
        .col-md-6.col-xs-12
          .panel.panel-default
            .panel-heading
              %h4
                Запили коллеге Pull request
            %ul.list-group
              %li.list-group-item
                1. Запили
                = link_to ZapiliCollegeGraphik.fork_endpoint do
                  Fork
                  %span.fa.fa-bitbucket
              %li.list-group-item 2. Запили свою фичу в отдельную ветку
              %li.list-group-item 3. Запили Pull request
        .clearfix
      .page-header.text-center
        %h4 Не знаешь, что такое issue или Pull request?
      .row
        .col-md-6.col-md-offset-3.col-xs-10.col-xs-offset-1
          #error-alert.alert.alert-danger.text-center.collapse{ aria: { expand: false } }
            %span.fa.fa-ban
            %strong Оппаньки, что-то пошло не так, попробуйте еще раз
            .help-block
              Если Вы неоднократно видите данное сообщение, сообщите, пожалуйста нам: #{ ZapiliCollegeGraphik.author_email }
          = form_for Feedback.new, remote: true, html: { class: 'form-horizontal' } do |f|
            .form-group
              .input-group
                .input-group-addon
                  %span.fa.fa-user
                = f.text_field :user_name, placeholder: 'Укажите Ваше имя', class: 'form-control', tabindex: 1, required: true
            .form-group
              .input-group
                .input-group-addon
                  %span.fa.fa-envelope
                = f.email_field :user_email, placeholder: 'Ваша почта, Коллега', class: 'form-control', tabindex: 2, required: true
            .form-group
              .input-group
                .input-group-addon
                  %span.fa.fa-font
                = f.text_area :body, placeholder: 'Текст предложения', class: 'form-control', rows: 5, tabindex: 3, required: true
            .form-group
              %button.submit.col-xs-12{ type: :submit, tabindex: 4 }
                %span.fa.fa-check
                Запилить!

          .help-block.text-center
            .text-danger
              *Ну или просто запили коллеге письмо :)
#request-processing-modal.modal.fade{ tabindex: -1, role: :dialog }
  .modal-dialog{ role: :document }
    #request-state-alert.alert.alert-info.text-center.collapse.in{ aria: { expand: true } }
      %strong Пожалуйста, подождите, Ваш запрос обрабатывается :)
    #success-alert.alert.alert-success.text-center.collapse{ aria: { expand: false } }
      %span.fa.fa-check-circle
      %strong Done

app/views/charts/new.html.haml
.col-xs-12
  .text-center
    = notice_message
  .page-header.text-center
    %h2
      Коллега, предоставьте данные для графика
.clearfix
.container
  .col-md-8.col-md-offset-2.col-xs-12.col-xs-offset-0
    = form_tag charts_path, multipart: true, class: 'form-horizontal', id: 'new_chart_form' do
      #file_field.form-group
        .col-md-8.col-md-offset-2.col-xs-12.col-xs-offset-0
          .input-group
            = file_field_tag 'chart[file]', accept: 'text/csv', class: 'form-control input-sm', data: { required: true, parent: '#file_field' }
            .input-group-addon .csv
      #title_field.form-group
        = label_tag 'chart[title]', 'Заголовок', class: 'col-md-2 col-md-offset-2 col-xs-4 col-xs-offset-0 control-label'
        .col-md-6.col-xs-8= text_field_tag 'chart[title]', '', placeholder: 'Введите заголовок', class: 'form-control input-sm', data: { required: true, parent: '#title_field' }
      .form-group
        = label_tag 'chart[subtitle]', 'Подзаголовок', class: 'col-md-2 col-md-offset-2 col-xs-4 col-xs-offset-0 control-label'
        .col-md-6.col-xs-8= text_field_tag 'chart[subtitle]', '', placeholder: 'Введите подзаголовок', class: 'form-control input-sm'
      .form-group
        = label_tag 'chart[y_axis]', 'Абсцисса', class: 'col-md-2 col-md-offset-2 col-xs-4 col-xs-offset-0 control-label'
        .col-md-6.col-xs-8= text_field_tag 'chart[y_axis]', '', placeholder: 'Значения по оси абсцисс', class: 'form-control input-sm'
      .form-group
        = label_tag 'chart[type]', 'График', class: 'col-md-2 col-md-offset-2 col-xs-4 col-xs-offset-0 control-label'
        .col-md-6.col-xs-8
          .btn-group.btn-group-justified{ data: { toggle: :buttons } }
            %label.btn.btn-default.active{ title: 'Spline Chart' }
              = radio_button_tag 'chart[type]', 'spline', true
              %span.fa.fa-line-chart
            %label.btn.btn-default{ title: 'Bar Chart' }
              = radio_button_tag 'chart[type]', 'bar'
              %span.fa.fa-bar-chart
            %label.btn.btn-default{ title: 'Area Chart' }
              = radio_button_tag 'chart[type]', 'area'
              %span.fa.fa-area-chart
      .form-group
        = label_tag 'chart[type]', 'Данные', class: 'col-md-2 col-md-offset-2 col-xs-4 col-xs-offset-0 control-label'
        .col-md-6.col-xs-8
          .btn-group.btn-group-justified
            %label.btn.btn-default.btn-sm.active
              Тип "А"
            %label.btn.btn-default.btn-sm.disabled{ title: 'Тип "B" не поддерживается на данный момент' }
              Тип "В"
            %label.btn.btn-default.btn-sm.disabled{ title: 'Тип "С" не поддерживается на данный момент' }
              Тип "C"
          .help-block
            = link_to 'Что это такое?', '#', data: { toggle: :modal, target: '#data-types-modal' }
      .form-group
        .col-md-8.col-md-offset-2.col-xs-12
          %button.btn.btn-primary.btn-block.submit-form{ type: :button, data: { submit_form: '#new_chart_form' } }
            %span.fa.fa-check
            ЗАПИЛИТЬ!

#data-types-modal.modal.fade.col-xs-8.col-xs-offset-2{ role: :dialog, tabindex: -1 }
  .modal-diallog{ role: :document }
    .modal-content
      .modal-header
        %button.close{ type: :button, data: { dismiss: :modal } } &times;
        %h4 Типы (структуры) данных
      .modal-body
        #data-types-accordion.panel-group
          .panel.panel-success
            .panel-heading
              = link_to '#data-type-a', role: :button, data: { toggle: :collapse, parent: '#data-types-accordion'} do
                Тип данных "А"
            #data-type-a.panel-collapse.collapse.in{ data: { parent: '#data-types-accordion' } }
              %table.table.table-striped
                %tbody
                  %tr
                    %td Валера
                    %td 2015-10-01
                    %td 10
                  %tr
                    %td
                    %td 2015-10-02
                    %td 15
                  %tr
                    %td
                    %td 2015-10-03
                    %td 10
                  %tr
                    %td
                    %td
                      %strong ...
                    %td
                      %strong ...
                  %tr
                    %td
                    %td 2015-10-25
                    %td 45
                  %tr
                    %td
                    %td 2015-10-26
                    %td 25
                  %tr
                    %td.text-center{ colspan: 3 }
                      %span.text-muted Пустая строка, как разделитель
                  %tr
                    %td Володя
                    %td 2015-10-01
                    %td 20
                  %tr
                    %td
                    %td 2015-10-02
                    %td 25
                  %tr
                    %td
                    %td 2015-10-03
                    %td 30
                  %tr
                    %td
                    %td
                      %strong ...
                    %td
                      %strong ...
                  %tr
                    %td
                    %td 2015-10-25
                    %td 11
                  %tr
                    %td
                    %td 2015-10-26
                    %td 50

          .panel.panel-warning
            .panel-heading
              = link_to '#data-type-b', role: :button, data: { toggle: :collapse, parent: '#data-types-accordion'} do
                Тип данных "B"
            #data-type-b.panel-collapse.collapse{ data: { parent: '#data-types-accordion' } }
              %table.table.table-striped
                %tbody
                  %thead
                    %tr
                      %th &nbsp;
                      %th 2015-10-01
                      %th 2015-10-02
                      %th 2015-10-03
                      %th
                        %strong ...
                      %th 2015-10-25
                      %th 2015-10-26
                  %tbody
                    %tr
                      %td Валера
                      %td 10
                      %td 15
                      %td 10
                      %td
                        %strong ...
                      %td 45
                      %td 25
                    %tr
                      %td Володя
                      %td 20
                      %td 25
                      %td 30
                      %td
                        %strong ...
                      %td 11
                      %td 50

          .panel.panel-warning
            .panel-heading
              = link_to '#data-type-c', role: :button, data: { toggle: :collapse, parent: '#data-types-accordion'} do
                Тип данных "C"
            #data-type-c.panel-collapse.collapse{ data: { parent: '#data-types-accordion' } }
              %table.table.table-striped
                %tbody
                  %thead
                    %tr
                      %th &nbsp;
                      %th Валера
                      %th Володя
                  %tbody
                    %tr
                      %td 2015-10-01
                      %td 10
                      %td 20
                    %tr
                      %td 2015-10-02
                      %td 15
                      %td 25
                    %tr
                      %td 2015-10-03
                      %td 10
                      %td 30
                    %tr
                      %td
                        %strong ...
                      %td
                        %strong ...
                      %td
                        %strong ...
                    %tr
                      %td 2015-10-25
                      %td 45
                      %td 11
                    %tr
                      %td 2015-10-26
                      %td 25
                      %td 50

app/views/charts/show.html.haml
.col-xs-12
  .text-center
    = notice_message

  .page-header.text-center
    %h2 Коллега, все готово!
  .clearfix

  - grid_class = @charts.count == 1 ? 'col-xs-8 col-xs-offset-2' : 'col-md-6 col-md-offset-0 col-xs-10 col-xs-offset-1'
  - @charts.each do |chart|
    %div{ class: grid_class }
      .chart-container
        .chart{ data: { type: chart.type, title: chart.title, subtitle: chart.subtitle, point_start: chart.point_start, series: chart.series.to_json, yaxis: chart.y_axis } }

  .clearfix
  .page-header
  .text-center
    = link_to 'ЕЩЕ ГРАФИК!', new_chart_path, class: 'btn btn-lg btn-primary'

app/views/home/index.html.haml
.col-xs-12
  .page-header.text-center
    %h1
      Запили коллеге график
    %h3.text-muted
      Сервис, который запилит коллеге график!
    = link_to 'ЗАПИЛИТЬ ГРАФИК!', new_chart_path, class: 'btn btn-lg btn-primary'
.clearfix
.charts.col-xs-12
  %h3.text-center Вот такие прекрасные графики запилим Вам с радостью!
  .blank-at-bottom
  .col-xs-12.col-md-6
    .chart-container
      #chart-example-0
  .col-xs-12.col-md-6
    .chart-container
      #chart-example-1
  .col-xs-12.col-md-6
    .chart-container
      #chart-example-2
  .col-xs-12.col-md-6
    .chart-container
      #chart-example-3
.clearfix
.text-center
  = link_to 'ЗАПИЛИТЬ ГРАФИК!', new_chart_path, class: 'btn btn-lg btn-primary'

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      = link_to root_path, class: 'navbar-brand' do
        %span.fa.fa-bar-chart
        Запили коллеге график

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Zapili College Graphik'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Zapili College Graphik'}"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = yield
    %footer
      .container.text-center
        = link_to about_index_path do
          %span.fa.fa-newspaper-o
          Запили коллеге график
        |
        \&copy; 2015 &ndash; Present
        .clearfix
        Version #{ ZapiliCollegeGraphik.version }